// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJk2gno_h1xSzzIeEgo6tfV504howJD1g',
    appId: '1:698045112061:web:d07d2031bf31dd7102a894',
    messagingSenderId: '698045112061',
    projectId: 'mcall-98ee6',
    authDomain: 'mcall-98ee6.firebaseapp.com',
    storageBucket: 'mcall-98ee6.firebasestorage.app',
    measurementId: 'G-PKD65RH48L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEQbWP_DNIMuSQRFgKouKirzTO_DNBrOg',
    appId: '1:698045112061:android:f76bfb457d36b50902a894',
    messagingSenderId: '698045112061',
    projectId: 'mcall-98ee6',
    storageBucket: 'mcall-98ee6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHpN9lSF9Q2tymXxWDbkO4SqJixPbfFcQ',
    appId: '1:698045112061:ios:9e7d3129a9cfd7c802a894',
    messagingSenderId: '698045112061',
    projectId: 'mcall-98ee6',
    storageBucket: 'mcall-98ee6.firebasestorage.app',
    iosBundleId: 'com.example.mCall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHpN9lSF9Q2tymXxWDbkO4SqJixPbfFcQ',
    appId: '1:698045112061:ios:9e7d3129a9cfd7c802a894',
    messagingSenderId: '698045112061',
    projectId: 'mcall-98ee6',
    storageBucket: 'mcall-98ee6.firebasestorage.app',
    iosBundleId: 'com.example.mCall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJk2gno_h1xSzzIeEgo6tfV504howJD1g',
    appId: '1:698045112061:web:21ea36a31ab3af0c02a894',
    messagingSenderId: '698045112061',
    projectId: 'mcall-98ee6',
    authDomain: 'mcall-98ee6.firebaseapp.com',
    storageBucket: 'mcall-98ee6.firebasestorage.app',
    measurementId: 'G-2S249HVQXD',
  );
}
